name: takwin
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  http: ^0.13.5
  just_audio: ^0.9.32
  audio_video_progress_bar: ^1.0.1
  just_audio_background: ^0.0.1-beta.9
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  just_audio_windows: ^0.2.0
  localstore: ^1.3.5
  uuid: ^3.0.7
  #flutter_downloader: ^1.10.2
  permission_handler: ^10.2.0
  android_path_provider: ^0.3.0
  device_info_plus: ^8.2.0
  flutter_file_downloader: ^1.1.2
  flutter_downloader: ^1.10.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/img/app-icon-48.png"
    icon_size: 48 # min:48, max:256, default: 48
flutter_native_splash:
  color: "#ffffff"
  image: assets/img/app-icon.png
  android: true
  ios: true 
flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/img/
  fonts:
    - family: Almarai
      fonts:
      - asset: assets/fonts/Almarai-Regular.ttf